name: Godot Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:4.7

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Verify Godot
        run: godot --version

      - name: Build Linux export
        run: |
          godot --headless --path . --export-release "Linux/X11" build/game.x86_64