name: Godot Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:4.7
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget unzip

      - name: Download Godot 4.7
        run: |
          wget -O godot.zip "https://downloads.godotengine.org/?version=4.7&flavor=stable&slug=linux.x86_64.zip&platform=linux.x86_64"
          unzip godot.zip
          chmod +x Godot_v4.7-stable_linux.x86_64

      - name: Export project
        run: |
          mkdir -p build
          ./Godot_v4.2.2-stable_linux.x86_64 --headless --quit --export-release "Linux/X11" build/game.x86_64